### PR TITLE
CSS edits on hover and links, global and project cards, progress bar

### PR DESCRIPTION
**Pull request by francespoblete**
Changes made:
Progress bar label (x/x)
Progress bar flipped and color changes
Font size and font style edits on project card
Project card tags color and hover color
Global link hover color

### CODE REVIEW

**Comment by Misty-W** [comment]
Nice updates @francespoblete! 

My only suggestion would be to make the "closed" portion of the progress bar white or light gray to stand out from the green background of the project card.

**Comment by francespoblete** [comment]
Thanks @Misty-W , I already updated the color based on your request :)

**Comment by Misty-W** [comment]
Thanks @francespoblete !

**Comment by natestemen** [comment]
Thanks for this Frances! I really like the new styling for tags, and the smaller borders around project cards.

The added padding around `a` tags makes inline links have quite awkward spacing: Screenshot 2023-06-07 at 9 50 31 AM

Any ideas what we could do here?

**Comment by natestemen** [comment]
I also noticed that the progress bars look very different on different browsers. Any idea how to make them the same?

| firefox | chrome |
| --- | --- |
| Screenshot 2023-06-07 at 9 54 01 AM | Screenshot 2023-06-07 at 9 54 41 AM |

**Comment by natestemen** [comment]
I think I fixed the second issue in https://github.com/unitaryfund/unitaryhack/commit/c9f14979003b4a0dd99cbf7dfd267685dda5ff1a.

**Comment by francespoblete** [comment]
Thanks for the fix @natestemen ! Do you think the progress bars make sense when it's showing you the open figures on the right side instead of the left? That's one reason why I flipped it because I feel like if we show it on the right, then it's clearer. About the inline link padding, I unfortunately do not have a solution to that. If we want the links to have the same hover effect as the nav, we have to add the padding, otherwise, the whole line moves on hover. Should we just make a simpler hover effect on in line links?

Screenshot 2023-06-08 at 09 34 07

**Comment by natestemen** [comment]
> Do you think the progress bars make sense when it's showing you the open figures on the right side instead of the left?

I was a little confused at first, but I think that's only because I was used to looking at it the other way. I think you're right though, and this may be better.

> Should we just make a simpler hover effect on in line links?

Yeah, I think having inline links styled more simply than the navigation links makes sense if you do too.

**Pull request merged**
